[package]
name = "bevy_zombie_test"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_life = {version = "0.11.0"}
noise = "0.9.0"
rand = "0.9.1"

[features]
default = ["bevy/bevy_sprite"]
